#pragma once

namespace GL::LL
{
    enum class UniformType
    {
        FLOAT,  VEC2,  VEC3,  VEC4,
        INT,   IVEC2, IVEC3, IVEC4,
        UINT,  UVEC2, UVEC3, UVEC4,
        BOOL,  BVEC2, BVEC3, BVEC4,
        MAT2,   MAT2x3, MAT2x4,
        MAT3x2, MAT3,   MAT3x4,
        MAT4x2, MAT4x3, MAT4,
        SAMPLER_2D, SAMPLER_3D, SAMPLER_CUBE, SAMPLER_2D_ARRAY,
        ISAMPLER_2D, ISAMPLER_3D, ISAMPLER_CUBE, ISAMPLER_2D_ARRAY,
        USAMPLER_2D, USAMPLER_3D, USAMPLER_CUBE, USAMPLER_2D_ARRAY,
        SAMPLER_2D_SHADOW, SAMPLER_2D_ARRAY_SHADOW, SAMPLER_CUBE_SHADOW,
        UNKNOWN,
    };
}
